### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by rweigel** [hapi-server/client-python#40]
The Makefile should use tox and tox-conda for testing on different versions of Python.

1. Currently, repository tests are done by creating conda virtual environments and then the package is tested using regular virtual environments.
2. The Windows tests need work. There is a step where libcrypto and libssl are copied to a different directory. The reason for this is not documented. Ideally, use of tox will allow this step to not be needed.

**Comment by KSR4599** [comment]
I have just pushed a branch ['tox-demo'](https://github.com/hapi-server/client-python/tree/tox-demo). It seems tox needs all the versions of interpreters (that we put in [envlist](https://github.com/hapi-server/client-python/blob/tox-demo/tox.ini#L3) i.e 2.7 and 3.8 in our case) to be existing. In order to integrate this setup with Travis-CI, I have allocated [jobs](https://github.com/hapi-server/client-python/blob/tox-demo/.travis.yml#L2-L50) such that all the three OS shall have the desired version of the interpreter (either 3.8 or 2.7) before triggering the script [**tox -e short-test**.](https://github.com/hapi-server/client-python/blob/tox-demo/.travis.yml#L54)  I have used the flag [skip_missing_interpreters](https://github.com/hapi-server/client-python/blob/tox-demo/tox.ini#L4) to avoid issues related to the other missing interpreter.
