### ISSUE TITLE
Inconsistent data return with parameters='' on CDAWeb

### ISSUE THREAD

**Issue by sandyfreelance** [hapi-server/client-python#49]
CDAWeb can fetch and plot specific items, but cannot fetch 'all data' (empty array, even though 'meta' is fully populated)

Fetching data from CDAWeb using the example code at the end of this email (from hapi_demo.py and accompanying Notebook)
   parameters='DST1800'  --> WORKS
   hapiplot(data,meta) WORKS
AND
   parameters='' --> returns full metadata but empty data []
  hapiplot(data,meta) is irrelevant because there is no data
 

```
# CDAWeb example
from hapiclient import hapi
from hapiplot import hapiplot
from hapiclient.util import pythonshell
 
server     = 'https://cdaweb.gsfc.nasa.gov/hapi'
dataset    = 'OMNI2_H0_MRG1HR' # See section 5 for information on finding list of datasets
start      = '2003-09-01T05:00:00Z'
stop       = '2003-12-01T06:00:00Z'
parameters = ''
#'DST1800' # See section 5 for information on finding parameters in dataset
opts       = {'logging': True, 'usecache': False}
 
# Get parameter data. See section 5 for for information on getting available datasets and parameters
data, meta = hapi(server, dataset, parameters, start, stop, **opts)
print(data)
hapiplot(data,meta)
```

The above call returns an empty data array.

The server will fetch all data via direct HAPI server call, e.g.:
https://cdaweb.gsfc.nasa.gov/hapi/data?id=AC_H0_SWE&time.min=2001-01-01T05:00:00Z&time.max=2001-01-01T06:00:00Z

```
2001-01-01T05:00:30.000Z,-1.0E31,279.68,-1.0E31,-1.0E31,-278.8,-8.5,20.4,278.8,11.2,19.1,-278.8,-8.7,17.2,1522482.0,165893.0,68385.0,1522482.0,160560.0,80109.0
2001-01-01T05:01:34.000Z,-1.0E31,279.28,-1.0E31,-1.0E31,-278.3,-7.4,22.0,278.3,10.2,20.8,-278.3,-7.6,18.9,1522483.0,165888.0,68389.0,1522483.0,160636.0,79950.0
2001-01-01T05:02:38.000Z,-1.0E31,280.29,-1.0E31,-1.0E31,-279.3,-8.4,22.1,279.3,11.2,20.8,-279.3,-8.6,18.9,1522484.0,165883.0,68392.0,1522484.0,160711.0,79791.0
[etc]
```

**Comment by sandyfreelance** [comment]
This is using hapiclient 0.2.3 and hapiplot 0.2.0

**Comment by rweigel** [comment]
The URL that you gave that returns data does not match the call made to CDAWeb. The URL associated with your code returns a HAPI 1201 error.

The problem appears to be with the CDAWeb HAPI server. To see this, set `logging=True` and `format=csv` (see code below) to see the URL and the file downloaded in the console. The downloaded file contains a HAPI error response of "no data for time range", in which case the response of `data=[]` makes sense.

This appears to be a server error because

`curl "https://cdaweb.gsfc.nasa.gov/hapi/data?id=OMNI2_H0_MRG1HR&parameters=BY_GSE1800&time.min=2003-09-01T05:00:00Z&time.max=2003-12-01T06:00:00Z"`

returns data but

`curl "https://cdaweb.gsfc.nasa.gov/hapi/data?id=OMNI2_H0_MRG1HR&parameters=&time.min=2003-09-01T05:00:00Z&time.max=2003-12-01T06:00:00Z"`

and, equivalently,

`curl "https://cdaweb.gsfc.nasa.gov/hapi/data?id=OMNI2_H0_MRG1HR&time.min=2003-09-01T05:00:00Z&time.max=2003-12-01T06:00:00Z"`

does not. I will send a report to the server contact listed at https://hapi-server.org/servers/#server=CDAWeb.


```
# CDAWeb example
from hapiclient import hapi
 
server     = 'https://cdaweb.gsfc.nasa.gov/hapi'
dataset    = 'OMNI2_H0_MRG1HR' 
start      = '2003-09-01T05:00:00Z'
stop       = '2003-12-01T06:00:00Z'
parameters = ''
opts       = {'logging': True, 'format': 'csv', 'usecache': False}
data, meta = hapi(server, dataset, parameters, start, stop, **opts)
print(data)
```

**Comment by rweigel** [comment]
The client should possibly warn that there are no data in the interval.

**Comment by berniegsfc** [comment]
The problem in the cdaweb hapi server seems to be that the dataset contains virtual variables (e.g., SIGMA-ABS_B1800) with characters that cdawlib renames (e.g., SIGMA$ABS_B1000).  If your request contains any of these variables (or all variables), the hapi server code can't find the variable because it is looking for the original name.

**Comment by rweigel** [comment]
This has been moved and tracked elsewhere.
